version: 1.0.{build}
image: Visual Studio 2019
build_script:
- cmd: mkdir build && cd build
- cmd: cmake -DVTIL_BUILD_TESTS=ON ..
- cmd: cmake --build . --config Release
test_script:
- cmd: VTIL-Tests\Release\VTIL-Tests.exe